seq = "ADEAAAACEDFDEBADFEAADDEAACEBACEACEACEAABACECEDDEDEADEDEBADCECEAAADEABAADFDEDEADEAABADDEDFEDEAADEABADFEDEADEADECEBACECEACEAACEBACECEACEDFDEDEABADFEDEAADFEDECEBACEACECEDDEDFEDEBADECECEACEACEBACEDDEDEAAAABACEACECEDDEDFEDEBADECECEACEAABACECEACEAAABAADFEDEAADFEDEBADEADECECEDDEDFEBADEDECEACECEDDEBADDEDFEDEAADEABAADDEDFEAAAABACECEACECEDFEABADDEDFEAADDDEDEDEBADCEADCECECEDDEDEBADEDECEADE"

# Replace ? with D (since it was ?CE and we fixed to DCE)
seq = seq.replace("?", "D")

# Try all possible 6-to-2 mappings (binary)
# Wait, 6 frequencies. If it's 7-bit ascii, it must be binary.
# But there are 6 frequencies! A, B, C, D, E, F.
# How can 6 frequencies map to binary?
# Maybe A, B, C are 0, and D, E, F are 1?
