server {
    listen 8888;
    server_name capyflag.local;

    location = /flag {
        default_type text/plain;
        alias /flag.txt;
    }

    location = /appflag {
        default_type text/plain;
        alias /app/flag.txt;
    }
}
