pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8888 default_server;
        listen 80 default_server;
        server_name _;

        location = /flag {
            default_type text/plain;
            alias /flag.txt;
        }

        location = /appflag {
            default_type text/plain;
            alias /app/flag.txt;
        }

        location / {
            default_type text/plain;
            return 200 "capy nginx alive\n";
        }
    }
}
