service ctf_diary
{
    type = UNLISTED
    protocol = tcp
    socket_type = stream
    port = 30080
    wait = no
    disable = no
    user = user
    server = /usr/bin/timeout
    server_args = --foreground 60s /home/user/diary
    log_on_success += USERID
    log_on_failure += USERID
}