# Wait, look at the hex string again!
# 55499d741336f9d6755749d741306555659a779a726b206a356b33121201306f13174552c133625574554913367131655573554996775573130771066f61679e205574967755736a36683563353e0d3e0d7e4320154a53368629464a340946c10633656366649c6e20335
# It is 213 characters long.
# What if it's a base 16 string, but it's actually just a string of hex digits?
# Yes, it's a string of hex digits.
# What if we map the 16 unique codons to the 16 hex digits?
# We did that, and we found 3 permutations that give a printable ASCII string ending in "CIT{99".
# The 3 strings are:
s1 = b'7\x7fuO2&u1>OM@Vl);QlurTM);TqCt%+~((+~Q[&"Q[&H)VLD)[H~)VHqU,-s%>OMFVmCt.&t((L_U,46*7\x7fu17\x7fuO>OM@QmCt.+~((&q((z Q)&"((&qU,4E3>OC\x7fVl+BQl)4-MurTM)\x7fTlurSl+-TW+%T\'+IT\'M4/\'M4/\'\'7%mC%.\x7ft[(Hq)-+HQ,+t[/zDQ,+_U,O*_7Qu/7Q),2&EW>LCIT{99'
s2 = b'7~uN2&u1?NM@Vl);QlurTM);TqCt%+\x7f((+\x7fQ[&"Q[&H)VLD)[H\x7f)VHqU,-s%?NMFVmCt/&t((L^U,46*7~u17~uN?NM@QmCt/+\x7f((&q((z Q)&"((&qU,4E3?NC~Vl+BQl)4-MurTM)~TlurSl+-TW+%T\'+IT\'M4.\'M4.\'\'7%mC%/~t[(Hq)-+HQ,+t[.zDQ,+^U,N*^7Qu.7Q),2&EW?LCIT{99'
s3 = b'7~uN2&u1=NO@Vl);QlurTO);TqCt%+}((+}Q[&"Q[&H)VLD)[H})VHqU,/s%=NOFVoCt-&t((L^U,46*7~u17~uN=NO@QoCt-+}((&q((z Q)&"((&qU,4E3=NC~Vl+BQl)4/OurTO)~TlurSl+/TW+%T\'+IT\'O4.\'O4.\'\'7%oC%-~t[(Hq)/+HQ,+t[.zDQ,+^U,N*^7Qu.7Q),2&EW=LCIT{99'

# Wait! The hex string we are trying to decode is NOT the hex string of the codepoints!
# The hex string we are trying to decode is the string of hex digits generated by mapping the 440 codons!
# 440 codons -> 440 hex digits -> 220 bytes.
# And the 220 bytes end in "CIT{99".
# But wait! If the 220 bytes end in "CIT{99", then the 220 bytes ARE the plaintext!
# But the 220 bytes look like gibberish!
# How can it be the plaintext if it looks like gibberish?
# Maybe the gibberish is just random padding, and the flag is at the end?
# If the flag is "CIT{99...", then the flag is cut off!
# Because the string ends with "CIT{99".
# Where is the rest of the flag?
# Maybe the string wraps around?
# "CIT{997~uN2&u1=NO@Vl);QlurTO);TqCt%+}((+}Q[&"Q[&H)VLD)[H})VHqU,/s%=NOFVoCt-&t((L^U,46*7~u17~uN=NO@QoCt-+}((&q((z Q)&"((&qU,4E3=NC~Vl+BQl)4/OurTO)~TlurSl+/TW+%T\'+IT\'O4.\'O4.\'\'7%oC%-~t[(Hq)/+HQ,+t[.zDQ,+^U,N*^7Qu.7Q),2&EW=L}"
# Does this look like a flag? No.

# What if the 220 bytes are NOT the plaintext?
# What if the 220 bytes are base85 encoded?
# We checked, it has characters outside base85.
# What if the 220 bytes are Base91 encoded?
# We checked, it has characters outside Base91.
# What if the 220 bytes are Base92 encoded?
# We checked, it has characters outside Base92.

# What if the 220 bytes are a custom base encoding?
# We checked, it's not Base52.

# What if the 220 bytes are a piece of text that has been encoded with a custom encoding?
# What if we just decode the 220 bytes as a sequence of 7-bit values?
# What if we just decode the 220 bytes as a sequence of 6-bit values?
# What if we just decode the 220 bytes as a sequence of 5-bit values?

# Let's count the number of unique characters in s3 again.
print("Unique chars in s3:", len(set(s3)))
# 52 unique characters.

# What if the string is a piece of text that has been encoded with a substitution cipher, but the alphabet is NOT A-Z?
# What if the alphabet is the 52 unique characters in the string?
# If it's a substitution cipher, we can break it!
# But we tried to break it with simulated annealing, and it failed.
# Why did it fail?
# Maybe the text is NOT English!
# Maybe the text is a piece of code!
# Maybe the text is a URL!

# Let's look at the original text again.
text = "啉鵴𓍯鵧啴鵴𓁥啥驷驲欠樵欳𒄠𓁯𓅴唬𓍢啴啉𓍧𓅥啳啉陷啳𓁷𐙯慧鸠啴陷啳樶栵挵㸍㸍繃𠅔ꔳ桢鑤ꍀ鑬𐘳散晤鱮𠌵"
# We know the codepoints concatenate to a hex string:
hex_str = "55499d741336f9d6755749d741306555659a779a726b206a356b33121201306f13174552c133625574554913367131655573554996775573130771066f61679e205574967755736a36683563353e0d3e0d7e4320154a53368629464a340946c10633656366649c6e20335"
# What if the hex string is a sequence of 8-bit values, but they are NOT ASCII?
# What if the hex string is a sequence of 6-bit values, and we decode it as Base64?
# We did that, it gave gibberish.
# What if the hex string is a sequence of 5-bit values, and we decode it as Base32?
# We did that, it gave gibberish.

# What if the hex string is a sequence of 4-bit values, and we group them into bytes?
# That's just decoding the hex string as bytes!
# We did that, it gave gibberish.

# What if the hex string is a sequence of 4-bit values, and we group them into 6-bit values?
# That's what we did with Base64.

# What if the hex string is a piece of code?
# What if it's a URL?

# What if the hex string is compressed with gzip?
# We tried zlib, bz2, lzma.

# What if the hex string is encrypted with AES?
# If it's encrypted with AES, we need a key.

# What if the hex string is encrypted with RC4?
# If it's encrypted with RC4, we need a key.

