# Let's look at the original hex string again.
hex_str = "55499d741336f9d6755749d741306555659a779a726b206a356b33121201306f13174552c133625574554913367131655573554996775573130771066f61679e205574967755736a36683563353e0d3e0d7e4320154a53368629464a340946c10633656366649c6e20335"

# It's 213 characters long.
# What if it's a base 16 string, but it's actually just a string of hex digits?
# Yes, it's a string of hex digits.
# What if we map the 16 unique codons to the 16 hex digits?
# We did that, and we found 3 permutations that give a printable ASCII string ending in "CIT{99".
# The 3 strings are:
s1 = b'7\x7fuO2&u1>OM@Vl);QlurTM);TqCt%+~((+~Q[&"Q[&H)VLD)[H~)VHqU,-s%>OMFVmCt.&t((L_U,46*7\x7fu17\x7fuO>OM@QmCt.+~((&q((z Q)&"((&qU,4E3>OC\x7fVl+BQl)4-MurTM)\x7fTlurSl+-TW+%T\'+IT\'M4/\'M4/\'\'7%mC%.\x7ft[(Hq)-+HQ,+t[/zDQ,+_U,O*_7Qu/7Q),2&EW>LCIT{99'
s2 = b'7~uN2&u1?NM@Vl);QlurTM);TqCt%+\x7f((+\x7fQ[&"Q[&H)VLD)[H\x7f)VHqU,-s%?NMFVmCt/&t((L^U,46*7~u17~uN?NM@QmCt/+\x7f((&q((z Q)&"((&qU,4E3?NC~Vl+BQl)4-MurTM)~TlurSl+-TW+%T\'+IT\'M4.\'M4.\'\'7%mC%/~t[(Hq)-+HQ,+t[.zDQ,+^U,N*^7Qu.7Q),2&EW?LCIT{99'
s3 = b'7~uN2&u1=NO@Vl);QlurTO);TqCt%+}((+}Q[&"Q[&H)VLD)[H})VHqU,/s%=NOFVoCt-&t((L^U,46*7~u17~uN=NO@QoCt-+}((&q((z Q)&"((&qU,4E3=NC~Vl+BQl)4/OurTO)~TlurSl+/TW+%T\'+IT\'O4.\'O4.\'\'7%oC%-~t[(Hq)/+HQ,+t[.zDQ,+^U,N*^7Qu.7Q),2&EW=LCIT{99'

# Wait! The hex string we are trying to decode is NOT the hex string of the codepoints!
# The hex string we are trying to decode is the string of hex digits generated by mapping the 440 codons!
# 440 codons -> 440 hex digits -> 220 bytes.
# And the 220 bytes end in "CIT{99".
# But wait! If the 220 bytes end in "CIT{99", then the 220 bytes ARE the plaintext!
# But the 220 bytes look like gibberish!
# How can it be the plaintext if it looks like gibberish?
# Maybe the gibberish is just random padding, and the flag is at the end?
# If the flag is "CIT{99...", then the flag is cut off!
# Because the string ends with "CIT{99".
# Where is the rest of the flag?
# Maybe the string wraps around?
# "CIT{997~uN2&u1=NO@Vl);QlurTO);TqCt%+}((+}Q[&"Q[&H)VLD)[H})VHqU,/s%=NOFVoCt-&t((L^U,46*7~u17~uN=NO@QoCt-+}((&q((z Q)&"((&qU,4E3=NC~Vl+BQl)4/OurTO)~TlurSl+/TW+%T\'+IT\'O4.\'O4.\'\'7%oC%-~t[(Hq)/+HQ,+t[.zDQ,+^U,N*^7Qu.7Q),2&EW=L"
# Does this look like a flag? No.

# What if the 220 bytes are NOT the plaintext?
# What if the 220 bytes are base85 encoded?
# Base85 uses 5 characters to encode 4 bytes.
# 220 / 5 = 44. 44 * 4 = 176 bytes.
# Let's try to decode s3 as base85!
# Ascii85 uses !-u and z.
# Z85 uses 0-9, a-z, A-Z, ., -, :, +, =, ^, !, /, *, ?, &, <, >, (, ), [, ], {, }, @, %, $, #.
# We checked, s3 contains '~', '|', '}'. These are NOT in Z85 or Ascii85.
# What about Base91?
# Base91 uses A-Z, a-z, 0-9, !#$%&()*+,./:;<=>?@[]^_`{|}~"
# It does not use -, ', \.
# But s3 contains -, ', \.
# What about Base92? Base122?

# What if the 220 bytes are a custom base encoding?
# What if the 220 bytes are a Vigenere cipher?
# What if the 220 bytes are a substitution cipher?
# We tried to break the substitution cipher, but it failed.

# What if the 440 codons map to something else?
# We mapped them to 16 hex digits.
# What if we map them to 16 characters?
# What if we map them to 4-bit values, and then group them by 5 bits to get Base32?
# 440 * 4 = 1760 bits.
# 1760 / 5 = 352 characters.
# 1760 / 8 = 220 bytes.
# What if the 1760 bits are a binary string, and we decode it as ASCII?
# That's exactly what we did when we grouped them by 8 bits (2 hex digits = 1 byte).
# And we got 220 bytes ending in "CIT{99".

# Wait. If the 220 bytes end in "CIT{99", maybe the flag is "CIT{99}"?
# But there is no '}'.
# What if the '}' is the next character, but we ran out of codons?
# Why would we run out of codons?
# Because the Morse code message ended!
# Let's check the end of the Morse code message.
