text = "GJZTYOZFYTccWBHFaBZYCcHFCFLPXQYHHQYaaODaaOTHWTRHaTYHWTFIHEGXYTcMWNLPDOPHHTUIHPbXGJZFGJZTYTccaNLPDQYHHOFHHZEaHODHHOFIHPSGYTLJWBQVaBHPEcZYCcHJCBZYKBQECKQXCAQTCAcPHAcPHAAGXNLXDJPaHTFHEQTaHQPaHZRaHQUIHTXUGaZHGaHHYOSKYTLTCFJJ"
n = len(text)
freqs = {c: text.count(c) for c in set(text)}
ic = sum(f * (f - 1) for f in freqs.values()) / (n * (n - 1))
print(f"IC: {ic}")
